server:
  port: 7001
spring:
  application:
    name: hello-langchain
app:
  ai:
    default-provider: ${AI_PROVIDER:deepseek}
    max-request-per-minute: ${AI_MAX_REQUEST_PER_MINUTE:20}
    providers:
      deepseek:
        base-url: ${DEEPSEEK_BASE_URL:https://api.deepseek.com}
        model-name: ${DEEPSEEK_MODEL_NAME:deepseek-v4-flash}
        api-key: ${DEEPSEEK_API_KEY}
      qwen:
        base-url: ${QWEN_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode/v1}
        model-name: ${QWEN_MODEL_NAME:qwen3.8-flash}
        api-key: ${QWEN_API_KEY}
      grok:
        base-url: ${GROK_BASE_URL:https://api.x.ai/v1}
        model-name: ${GROK_MODEL_NAME:grok-3-mini}
        api-key: ${GROK_API_KEY}